
class const_crms:
    PTAD_MA = 1;
    PTAD_KHOANG_GIA_TRI = 2;
    LOAI_HINH_NK = 1;
    LOAI_HINH_XK = 2;
    QLT_PARAMS_PLXEPHANG = "QLT_PARAMS_PLXEPHANG"
    CO_TK = 1
    ID_NHOM_DEFAULT = "C"
    ISAPDUNGCHENHLECHTHUE = 1
    BATCH_SIZE = 50000
    NUMBER_RECORD_PROCESS = 5000
    IS_TINHLAI = 1


## HSDN params
class const_hsdn_params:
    QLT_PARAMS_HSDN_TC_MOTA = "QLT_PARAMS_HSDN_TC_MOTA"
    QLT_PARAMS_HSDN_DGTC = "QLT_PARAMS_HSDN_DGTC"
    QLT_PARAMS_HSDN_PLDCC = "QLT_PARAMS_HSDN_PLDCC"
    QLT_PARAMS_HSDN_PTAD = "QLT_PARAMS_HSDN_PTAD"
    QLT_MIN_MAX_ID = "QLT_MIN_MAX_ID"

## HSVP params
class const_hsvp_params:
    QLT_PARAMS_HSVP_HSPLTN = "QLT_PARAMS_HSVP_HSPLTN"
    QLT_PARAMS_HSVP_HSPLXNK = "QLT_PARAMS_HSVP_HSPLXNK"
    QLT_PARAMS_HSVP_PLCLT = "QLT_PARAMS_HSVP_PLCLT"
    QLT_PARAMS_HSVP_PLHSVP = "QLT_PARAMS_HSVP_PLHSVP"
    QLT_PARAMS_HSVP_PLSLVP = "QLT_PARAMS_HSVP_PLSLVP"
    QLT_PARAMS_HSVP_PLTLVP = "QLT_PARAMS_HSVP_PLTLVP"
    QLT_PARAMS_HSVP_PLVP = "QLT_PARAMS_HSVP_PLVP"
    QLT_PARAMS_HSVP_PLVPKTK = "QLT_PARAMS_HSVP_PLVPKTK"
    QLT_HSVP_SOTOKHAIDUOCTHONGQUAN = "QLT_HSVP_SOTOKHAIDUOCTHONGQUAN"
    QLT_HSVP_VIPHAMTOKHAI ="QLT_HSVP_VIPHAMTOKHAI"

